use std::collections::HashMap;

use crate::{
    ir::{
        Declaration, Function, Module,
        access::access,
        error::IRErrorInfo,
        generics::{self, generics},
        guard::guard,
        initialize_struct::initialize_struct,
        is::is,
    },
    parser::expression::{Expr, InfoExpr},
};

use crate::ir::{
    block::compile_block, call::call, conditional::conditional, index::index, literal::literal,
    returns::returns, variable::variable, variable_declaration::variable_declaration,
};

pub fn to_ir(
    function: &mut Function,
    block: &mut usize,
    module: &mut Module,
    expr: InfoExpr,
    store: Option<usize>,
    declarations: &HashMap<String, Declaration>,
    locals: &mut HashMap<String, Declaration>,
    next_var: &mut usize,
    tail: bool,
) -> Result<(), IRErrorInfo> {
    match expr.expr {
        Expr::Generics(base, params) => generics(
            base,
            params,
            function,
            block,
            module,
            store,
            declarations,
            locals,
            next_var,
            false,
        ),
        Expr::Literal(lit) => literal(lit, function, block, store),
        Expr::Access(left, right) => access(
            left,
            right,
            expr.idx,
            function,
            block,
            module,
            store,
            declarations,
            locals,
            next_var,
        ),
        Expr::Let(name, value_expr) => variable_declaration(
            name,
            value_expr,
            function,
            block,
            module,
            store,
            declarations,
            locals,
            next_var,
        ),
        Expr::Block(statements, returns) => compile_block(
            statements,
            returns,
            function,
            block,
            module,
            store,
            declarations,
            locals,
            next_var,
            tail,
        ),
        Expr::InitializeStruct(name, fields) => initialize_struct(
            name,
            fields,
            function,
            block,
            module,
            store,
            declarations,
            locals,
            next_var,
        ),
        Expr::Return(value_expr) => returns(
            value_expr,
            function,
            block,
            module,
            store,
            declarations,
            locals,
            next_var,
        ),
        Expr::Call(callee, args) => call(
            callee,
            args,
            function,
            block,
            module,
            store,
            declarations,
            locals,
            next_var,
            tail,
        ),
        Expr::Name(name) => variable(
            name,
            expr.idx,
            function,
            block,
            module,
            store,
            declarations,
            locals,
            next_var,
        ),
        Expr::If { cond, then, els } => conditional(
            cond,
            then,
            els,
            expr.idx,
            function,
            block,
            module,
            store,
            declarations,
            locals,
            next_var,
            tail,
        ),
        Expr::Guard { dependency, body } => guard(
            dependency,
            body,
            expr.idx,
            function,
            block,
            module,
            store,
            declarations,
            locals,
            next_var,
            tail,
        ),
        Expr::Index(left, right) => index(
            left,
            right,
            expr.idx,
            function,
            block,
            module,
            store,
            declarations,
            locals,
            next_var,
        ),
        Expr::Is { name, typ } => is(
            name,
            typ,
            expr.idx,
            function,
            block,
            module,
            store,
            declarations,
            locals,
            next_var,
        ),
    }
}
